<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GejalaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $gejala = [

            [
                'kode_gejala' => 'G01',
                'nama_gejala' => 'Demam',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G02',
                'nama_gejala' => 'Bagian rongga mulut terdapat bercak putih',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G03',
                'nama_gejala' => 'Pilek',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G04',
                'nama_gejala' => 'Mata merah dan berair',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G05',
                'nama_gejala' => 'Kemerahan pada kulit',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G06',
                'nama_gejala' => 'Diare',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G07',
                'nama_gejala' => 'Tidak nafsu makan',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G08',
                'nama_gejala' => 'Mual',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G09',
                'nama_gejala' => 'Muntah',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G10',
                'nama_gejala' => 'Adanya cacing pada tinja',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G11',
                'nama_gejala' => 'Adanya darah pada feses',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G12',
                'nama_gejala' => 'Berat badan menurun 10% dibawah rentang ideal',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G13',
                'nama_gejala' => 'Pertumbuhan gigi dan tubuh terlambat',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G14',
                'nama_gejala' => 'Pertumbuhan tulang terlambat',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G15',
                'nama_gejala' => 'Lemas',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G16',
                'nama_gejala' => 'Ketika dipanggil nama tidak merespon',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G17',
                'nama_gejala' => 'Tidak dapat menunjuk benda',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G18',
                'nama_gejala' => 'Belum bisa berbicara dibawah 3 tahun',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G19',
                'nama_gejala' => 'Kesulitan tidur',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G20',
                'nama_gejala' => 'Tidak fokus',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G21',
                'nama_gejala' => 'Suka melakukan kegiatan berulang-ulang',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G22',
                'nama_gejala' => 'Sulit bila digendong',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G23',
                'nama_gejala' => 'Menolak untuk dipeluk',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G24',
                'nama_gejala' => 'Suka menangis dan tertawa tanpa sebab',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G25',
                'nama_gejala' => 'Tidak mau menatap mata',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G26',
                'nama_gejala' => 'Suka memainkan jari didepan mata',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G27',
                'nama_gejala' => 'Suka bermain dengan cahaya',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G28',
                'nama_gejala' => 'Mata mengecil',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G29',
                'nama_gejala' => 'Kejang',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G30',
                'nama_gejala' => 'Kesulitan bernapas',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G31',
                'nama_gejala' => 'Ukuran kepala besar',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G32',
                'nama_gejala' => 'Ubun-ubun kepala mencembung',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G33',
                'nama_gejala' => 'Mudah marah',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G34',
                'nama_gejala' => 'Rambut rontok',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G35',
                'nama_gejala' => 'Kulit kering dan kasar',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G36',
                'nama_gejala' => 'Pusing',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G37',
                'nama_gejala' => 'Merasakan lapar terus-menerus',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G38',
                'nama_gejala' => 'Kesulitan berjalan',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G39',
                'nama_gejala' => 'Gerakan tubuh tidak terkontrol',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G40',
                'nama_gejala' => 'Otot terasa kaku',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G41',
                'nama_gejala' => 'Kesulitan berbicara',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G42',
                'nama_gejala' => 'Kesulitan menggerakan anggota tubuh',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G43',
                'nama_gejala' => 'Kesulitan merangkai kata-kata',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G44',
                'nama_gejala' => 'Kesulitan mengucapkan kata-kata panjang',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G45',
                'nama_gejala' => 'Menghilangkan konsonan kata awal dan akhir',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G46',
                'nama_gejala' => 'Selalu berjuang untuk membuat kata-kata',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G47',
                'nama_gejala' => 'Lebih suka menggunakan komunkasi non-verbal secara berlebihan',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G48',
                'nama_gejala' => 'Banyak berbicara',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G49',
                'nama_gejala' => 'Gelisah',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G50',
                'nama_gejala' => 'Tidak bisa diam',
                'penting' => false,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G51',
                'nama_gejala' => 'Mudah merasa bosan',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G52',
                'nama_gejala' => 'Tidak bisa menjaga kontak mata',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G53',
                'nama_gejala' => 'Seringkali berjalan mondar-mandir tanpa tujuan',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G54',
                'nama_gejala' => 'Permintaan harus segeri dipenuhi',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G55',
                'nama_gejala' => 'Kesulitan membedakan bunyi yang mirip',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G56',
                'nama_gejala' => 'Kesulitan memahami pembicaraan',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G57',
                'nama_gejala' => 'Kesulitan menemukan sumber suara',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
            [
                'kode_gejala' => 'G58',
                'nama_gejala' => 'Kesulitan mengingat perintah yang diucapkan',
                'penting' => true,
                'created_at' => new \DateTime,
                'updated_at' => null,
            ],
        ];

        DB::table('gejalas')->insert($gejala);
    }
}
